# Penilaian Barang Milik Negara


## Apa itu penilaian?

Penilaian adalah proses kegiatan untuk memberikan suatu opini nilai atas suatu objek  penilaian pada saat tertentu.

## Siapakah Penilai Pemerintah?

Penilai Pemerintah adalah Pegawai Negeri Sipil di lingkungan Direktorat Jenderal Kekayaan Negara yang diberi tugas, wewenang, dan tanggung jawab untuk melakukan Penilaian, termasuk atas hasil Penilaiannya secara independen sesuai dengan ketentuan peraturan perundang-undangan.


## Barang apa saja yang bisa dinilai oleh Penilai Pemerintah pada KPKNL?

Penilai Pemerintah pada KPKNL berwenang untuk melakukan Penilaian terhadap objek Penilaian yang berada di wilayah kerjanya, meliputi: 

a.	Penilaian Barang Milik Negara pada Pengguna Barang/ Kuasa Pengguna Barang yang kewenangan pengelolaannya berada pada Kepala KPKNL;  
b.	Penilaian Barang Milik Negara pada Pengguna Barang yang kewenangan pengelolaannya telah dilimpahkan kepada Pengguna Barang;  
c.	Penilaian Barang Milik Negara pada Pengelola Barang;  
d.	Penilaian dalam rangka pengelolaan aset Badan Layanan Umum/Badan Layanan Umum Daerah;  
e.	Penilaian Barang Milik Negara/Daerah berupa bongkaran;  
f.	Penilaian Barang Milik Negara yang berasal dari barang rampasan negara;   
g.	Penilaian Barang Milik Negara yang berasal dari barang gratifikasi;   
h.	Penilaian Barang Milik Negara yang berasal dari aset eks kepabeanan dan cukai;  
i.	Penilaian Benda Sitaan;  
j.	Penilaian Barang Jaminan dan / atau Harta Kekayaan Lain;  
k.	Penilaian ABMA/T;  
l.	Penilaian barang yang akan ditetapkan status penggunaannya menjadi Barang Milik Negara;  
m.	Penilaian kekayaan negara lain-lain;  
n.	Penilaian Barang Milik Daerah dan/ atau kekayaan daerah pada Pemerintah Kota/Kabupaten/Desa;  
o.	Penilaian dalam rangka pengelolaan aset Badan Usaha Milik Daerah / Desa yang didalamnya terdapat saham milik Pemerintah Kota/Kabupaten/Desa;   
p.	Penilaian barang yang akan menjadi Barang Milik Negara/Daerah melalui cara pembelian, pembebasan, atau hibah tanpa perolehan;  
q.	Penilaian barang yang akan menjadi Barang Milik Negara/Daerah melalui cara tukar menukar yang proses tukar menukarnya menjadi kewenangan Kepala KPKNL;   
r.	Penilaian sumber daya alam yang berada pada wilayah kerjanya; dan   
s.	Penilaian dalam rangka penyelenggaraan pemerintahan negara atau pelaksanaan kebijakan Pemerintah Pusat berdasarkan penugasan Menteri atau Direktur Jenderal.


## Bagaimana prosedur permohonan penilaian terhadap BMN/BMD?

Proses permohonan penilaian BMN/D adalah sebagai berikut:  
1. Permohonan penilaian diajukan secara tertulis kepada Kepala KPKNL. Permohonan tersebut disertai dengan:  

a. identitas objek yang dimohonkan;  
b. jenis nilai yang dimohonkan; dan  
c. data dan informasi yang terkait dengan objek yang dimohonkan.
    
2. KPKNL akan melakukan verifikasi atas permohonan tersebut. Apabila data yang disampaikan dalam permohonan tidak lengkap, KPKNL akan menyampaikan surat permintaan kelengkapan data. Apabila permohonan lengkap, KPKNL akan memberitahukan rencana/jadwal penilaian.


## Berapa lama laporan penilaian dapat diselesaikan?

Jangka waktu penyelesaian laporan penilaian adalah sebagai berikut:  

a. 20 (Dua Puluh) hari kerja untuk penilaian BMN dalam rangka penyusunan neraca pemerintah pusat, sejak berakhirnya pelaksanaan survei lapangan.  
b. 25 (Dua Puluh Lima) hari kerja untuk penilaian BMN dalam rangka pemanfaatan, sejak berakhirnya pelaksanaan survei lapangan.  
c. 15 (Lima Belas) hari kerja untuk penilaian BMN dalam rangka Pemindahtanganan, sejak berakhirnya pelaksanaan survei lapangan.  
d. 20 (Dua Puluh) hari kerja untuk penilaian BMN dalam rangka pelaksanaan kegiatan lain sesuai ketentuan Peraturan Perundang-undangan, sejak berakhirnya pelaksanaan survei lapangan.
